### ISSUE TITLE
Read .swiftlint.yml rules

### ISSUE THREAD

**Issue by marsha97** [norio-nomura/action-swiftlint#19]
Hello, do we able to config this with rules which are stated in `.swiftlint.yml`?
If so, how do we do it?
thanks 😃

**Comment by norio-nomura** [comment]
As far as I tested, action-swiftlint uses `.swiftlint.yml` without applying #20.
Actual log:
https://github.com/norio-nomura/ObjectEncoder/commit/c84a68009b3f5ded487a83b77a9115b41867342f/checks?check_suite_id=294246724#step:4:3

**Comment by marsha97** [comment]
thanks for the reply. 
It is not being read when using master branch...

![image](https://user-images.githubusercontent.com/22322537/72215703-3f5a7900-3549-11ea-872c-375e3ef4d773.png)

I will try to figure it out again then.
Thank you :smiley:

**Comment by norio-nomura** [comment]
FYI, you can explicitly pass `--config /path/to/.swiftlint.yml` as arguments to action-swiftlint like following:
```yml
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.0.1
        with:
          args: --config /path/to/.swiftlint.yml
```
