### ISSUE TITLE
Option to run swiftlint only on changed files regression?

### ISSUE THREAD

**Issue by zntfdr** [norio-nomura/action-swiftlint#23]
Hi!
I'm using this action with the latest update that lints only files that have been changed in the PR.

This is great and it's a very nice addition! 

However, if now a PR has changes in files within an excluded folder, for example a `tests` folder, those files will also be linted, regardless of the `.swiftlint.yml` configuration.

Is this the expected behaviour?

Thank you in advance,
Federico

(cc @axelguilmin)

**Comment by norio-nomura** [comment]
Providing paths to SwiftLint via commandline will override `.swiftlint.yml`.
If you use `excluded`, you may be able to solve it using the` --force-exclude` option:
```yaml
       - name: GitHub Action for SwiftLint (Only files changed in the PR)
         uses: norio-nomura/action-swiftlint
         with:
           args: --force-exclude
         env:
           DIFF_BASE: ${{ github.base_ref }}
```

**Comment by zntfdr** [comment]
Thank you Norio san, I will try and let you know this Monday :)

**Comment by zntfdr** [comment]
Thank you again Norio-san, it seems to be working now 🙌

**Comment by badrinathvm** [comment]
This solution works, Thank you so much.

**Comment by tumata** [comment]
Adding this part is giving me error "fatal: Not a valid object name master"
`DIFF_BASE: ${{ github.base_ref }}`

**Comment by henry2423** [comment]
> Adding this part is giving me error "fatal: Not a valid object name master"
> `DIFF_BASE: ${{ github.base_ref }}`

@tumata, I fetch the base ref manually. And use my [custom action-swiftlint](https://github.com/henry2423/action-swiftlint), which [check the changed files](https://github.com/henry2423/action-swiftlint/blob/Fix-PR-Lint/entrypoint.sh) between `HEAD(set from actions/checkout, a merged PR)` and `base_ref(master)`. It works for me.

```
...
on: pull_request
...
      - uses: actions/checkout@v2
      - name: Fetch base ref
        run: |
          git fetch --prune --no-tags --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/heads/${{ github.base_ref }}
      - name: SwiftLint (Only files changed in the PR)
        uses: henry2423/action-swiftlint@Fix-PR-Lint
        with:
          args: --force-exclude --strict
        env:
           DIFF_BASE: ${{ github.base_ref }}
           DIFF_HEAD: HEAD
```
