### ISSUE TITLE
Swiftlint is still checking unchanged files

### ISSUE THREAD

**Issue by stefangerard** [norio-nomura/action-swiftlint#27]
SwiftLint is still checking unchanged files in my pull-requests even though I'm using the following swiftlint.yml config

```
name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
      - '!Pods/**'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.1.0
        env:
          DIFF_BASE: ${{ github.base_ref }}

**Comment by samh-depop** [comment]
I have the same issue.  
I get this error message 

> fatal: Not a valid object name dev

dev is the value in ${{ github.base_ref }}

Anyway to fix that?

**Comment by kerrmarin** [comment]
Same issue here!

**Comment by dlackty** [comment]
@samh-depop @kerrmarin I've solved this problem with following action configs:

```
      - name: Fetch base ref
        run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}
      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --force-exclude
        env:
          DIFF_BASE: origin/${{ github.base_ref }}
```
