### ISSUE TITLE
SwiftLint checking Pods even though .swiftlint.yml excludes them.

### ISSUE THREAD

**Issue by ApplebaumIan** [norio-nomura/action-swiftlint#28]
my .swiftlint.yml file:
```yaml
disabled_rules: # rule identifiers to exclude from running
opt_in_rules: # some rules are only opt-in
  - missing_docs
  # Find all the available rules by running:
  # swiftlint rules
 
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
missing_docs:
  error:
  - public
  warning:
  - internal
  - private
line_length: 
  warning: 230
  error: 500
  ignores_comments: true
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - vc
    - URL
    - GlobalAPIKey
    - i
    - db
    - url
    - row
    - key
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
```

my GitHub action
```yaml
name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: 
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.1.0
        env:
          DIFF_BASE: ${{ github.base_ref }}
```
