### ISSUE TITLE
Checking only Files in PR - .swiftlint.yml is not respected

### ISSUE THREAD

**Issue by ben-ole** [norio-nomura/action-swiftlint#32]
When using the configuration option

```
env:
 - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.1.0
      env:
        DIFF_BASE: ${{ github.base_ref }}
      with:
        args: --strict
```

in order to check only files of the current PR, my `.swiftlint.yml` configuration (containing some exclusion filters) is not taken into account. 

Removing the line `DIFF_BASE: ${{ github.base_ref }}` re-enables my `.swiftlint.yml` configuration.
