### ISSUE TITLE
Can't run GitHub Action for SwiftLint (Only files changed in the PR)

### ISSUE THREAD

**Issue by lactuannn** [norio-nomura/action-swiftlint#43]
When using the configuration option 

``` 
     - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
```

I got this errors. 
![Screenshot 2023-06-23 at 10 22 45](https://github.com/norio-nomura/action-swiftlint/assets/22000465/f32d7e64-aec3-4b20-9679-9d72dffb42e9)

I tried some solutions on Stackoverflow like: 
`git config --global --add safe.directory '*'` 
or 
`git config --system --add safe.directory '*'`
But it doesn't work...
