### ISSUE TITLE
Can't use SwiftLint file in repo

### ISSUE THREAD

**Issue by eonist** [norio-nomura/action-swiftlint#46]
https://github.com/eonist/TestRunner/blob/master/.github/workflows/Tests.yml

But it uses some other SwiftLint file, not the one in the project, any idea how to fix this?

My workflow looks like this: 

```yml
name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   #Something wrong with swiftlint action, figure it out later
  SwiftLint: ## Adds swift-linting to GH actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --config .swiftlint.yml
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
```
