### ISSUE TITLE
Won't work on Github CI

### ISSUE THREAD

**Issue by artemnovichkov** [norio-nomura/action-swiftlint#7]
I tried to use the action on Github CI, but it won't work. Here is my workflow:
```yml
on: pull_request
name: Lint
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: norio-nomura/action-swiftlint@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
In log I see the error message: ```Current Action `norio-nomuraaction-swiftlint` not found!```
